### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function setTestResult() on null

### ISSUE THREAD

**Issue by SavaKatic** [10up/wp_mock#147] opened 2019-10-27 11:35 UTC
WP-Mock 0.4.2
PHP 7.3.10
PHPUnit 8.4.1
Same as #128 , the same problem occurs on newer versions as well.
I added setUp and tearDown methods to a test case extending WP_Mock\Tools\TestCase. Running the PHPUnit gives  "Fatal error: Uncaught Error: Call to a member function setTestResult() on null". I used command-line interface of phpunit and installed it using composer.
Also, as OP stated, If I add parent::run($result) to line 303 of WP_Mock\Tools\TestCase it works as expected.

**Comment by mytuny** [comment] 2019-10-29 14:36
I had the same issue and I got it fixed by adding the line `WP_Mock::bootstrap();` to the `bootstrap.php.dist` file so it looks something like this:
```
<?php

require_once __DIR__ . '/vendor/autoload.php';

WP_Mock::setUsePatchwork( false );
WP_Mock::bootstrap();
```
I use **PHP 7.1.26** and **PHPUnit 7.0**

**Comment by rumur** [comment] 2020-03-29 11:09
Hi All!

I've also got this issue. 
And I noticed that this issue occurs each time when you run the  tests with the flag `--no-configuration`
it might happen when you run the specific test independently., however, if you run all scripts with the flag `--configuration`, in this case, the `test/bootstrap.php` file is also included and the `WP_Mock::bootstrap()` can instantiate all its dependencies correctly. 

**How to solve that issue?**

If you're using a PHPStorm, just set up the `Test Runner` options manually. 
go to `PHPStorm -> Preferences -> Languages and Frameworks -> PHP -> Test Frameworks` you can see on a screenshot.

![image](https://user-images.githubusercontent.com/15267625/77847532-fe741700-71bd-11ea-9f4d-01f72eba686e.png)

**Comment by rneudorf-godaddy** [comment] 2022-09-07 21:50
Duplicate of #128 

@mytuny is correct `WP_Mock::bootstrap()` needs to be added to a custom `bootstrap.php` when extending `WP_Mock\Tools\TestCase`. 

@rumur's suggestion to use PHPStorm's "default bootstrap file" setting will work. You can also use the `--bootstrap` option from the CLI or update `phpunit.xml`

@unfulvio-godaddy @nmolham-godaddy this issue can be closed.

**Closed** 2022-09-12 15:58 UTC
Labels: bug, help wanted
